Epmldi 1429
lean-delivery/ansible-role-mysql pull request #1
Opened 2018-12-10 15:26 UTC by tgadiev

Initial PR.
MySQL 5.5, 5.6, 5,7 and MariaDB supported
CentOS 6 and CentOS 7 supported.

2018-12-10 15:41 UTC, tgadiev commented
Initial PR.
MySQL 5.5, 5.6, 5,7 and MariaDB supported
CentOS 6 and CentOS 7 supported.

2018-12-11 11:09 UTC, ViachaslauKabak requested changes

2018-12-11 11:09 UTC, ViachaslauKabak commented on tasks/clear_innodb_logs.yml
> +- name: Stop MySQL to change configs
All name: values should be in double quotes

2018-12-11 11:09 UTC, ViachaslauKabak commented on meta/main.yml
> +  company: "Epam"
EPAM Systems

2018-12-11 11:09 UTC, ViachaslauKabak commented on meta/main.yml
> +  author: Epam
author: "Lean Delivery team <team@lean-delivery.com>"

2018-12-11 11:09 UTC, ViachaslauKabak commented on meta/main.yml
> +  min_ansible_version: 2.4
2.5.13?

2018-12-11 11:09 UTC, ViachaslauKabak commented on meta/main.yml
> +  issue_tracker_url: "https://github.com/lean-delivery/ansible-role-jenkins/issues"
seems that url is wrong

2018-12-11 11:09 UTC, ViachaslauKabak commented on tasks/main.yml
> +- name: Check whether the playbook can run on this OS
why we need this?

2018-12-11 11:09 UTC, ViachaslauKabak commented on vars/RedHat-6-mariadb.yml
> +mysql_version: latest
should it be in defaults? we cannot define version in playbook

2018-12-11 11:09 UTC, ViachaslauKabak commented on vars/RedHat-6-mysqld.yml
> +mysql_version: 5.7
should it be in defaults? we cannot define version in playbook

2018-12-11 11:09 UTC, ViachaslauKabak commented on vars/RedHat-7-mariadb.yml
> +mysql_version: latest
should it be in defaults? we cannot define version in playbook

2018-12-11 11:09 UTC, ViachaslauKabak commented on vars/RedHat-7-mysqld.yml
> +mysql_version: 5.7
should it be in defaults? we cannot define version in playbook

2018-12-11 11:09 UTC, ViachaslauKabak commented on tasks/clear_innodb_logs.yml
> +- name: Wait until the lock file is removed
Seems that the same was in handlers

2018-12-11 11:32 UTC, tgadiev commented on tasks/clear_innodb_logs.yml
> +- name: Wait until the lock file is removed
Yes, but it's not handler

2018-12-11 11:34 UTC, tgadiev commented on tasks/main.yml
> +- name: Check whether the playbook can run on this OS
It's to correctly handle unsupported OS run

2018-12-11 13:43 UTC, mckate commented on tasks/clear_innodb_logs.yml
> +- name: Wait until the lock file is removed
it should be

2018-12-12 06:03 UTC, ViachaslauKabak requested changes

2018-12-12 06:03 UTC, ViachaslauKabak commented on vars/RedHat-6-mariadb.yml
> +mysql_version: latest
If we keep variable here - so it supersedes value in defaults and playbook

2018-12-12 06:03 UTC, ViachaslauKabak commented on vars/RedHat-6-mysqld.yml
> +mysql_version: 5.7
If we keep variable here - so it supersedes value in defaults and playbook

2018-12-12 06:03 UTC, ViachaslauKabak commented on vars/RedHat-6-mysqld.yml
> +mysql_daemon: mysqld
If we keep variable here - so it supersedes value in defaults and playbook

2018-12-12 06:03 UTC, ViachaslauKabak commented on vars/RedHat-6-mysqld.yml
> +mysql_repo: http://repo.mysql.com/yum/mysql-{{ mysql_version }}-community/el/6/$basearch/
If we keep variable here - so it supersedes value in defaults and playbook

2018-12-12 06:03 UTC, ViachaslauKabak commented on vars/RedHat-6-mysqld.yml
> +mysql_gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
If we keep variable here - so it supersedes value in defaults and playbook

2018-12-12 06:03 UTC, ViachaslauKabak commented on vars/RedHat-6-mariadb.yml
> +mysql_daemon: mariadb
If we keep variable here - so it supersedes value in defaults and playbook

2018-12-12 06:03 UTC, ViachaslauKabak commented on vars/RedHat-6-mariadb.yml
> +mysql_packages:
If we keep variable here - so it supersedes value in defaults and playbook

2018-12-12 06:03 UTC, ViachaslauKabak commented on vars/RedHat-6-mariadb.yml
> +mysql_service_name: mysql
If we keep variable here - so it supersedes value in defaults and playbook

2018-12-12 06:03 UTC, ViachaslauKabak commented on vars/RedHat-6-mariadb.yml
> +mysql_python_packages:
If we keep variable here - so it supersedes value in defaults and playbook

2018-12-12 06:03 UTC, ViachaslauKabak commented on vars/RedHat-6-mariadb.yml
> +mysql_slow_query_log_file: /var/log/mysql-slow.log
If we keep variable here - so it supersedes value in defaults and playbook

2018-12-12 06:29 UTC, ViachaslauKabak approved these changes

2018-12-13 09:02 UTC, arno49 approved these changes

2018-12-13 09:02 UTC, arno49 commented on README.md
> +  - Supported OS:
what about RHEL ?

2018-12-13 09:02 UTC, merged