Corrections for correct work with ansible 2.8. Removed Debian 8 from support. Refactoring
lean-delivery/ansible-role-mysql pull request #12
Opened 2019-07-24 11:49 UTC by y6vmeq

## Description

Corrections for correct work with ansible 2.8. Removed Debian 8 from support. Refactoring

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Reviews

- [X] @tgadiev 
- [X] @pavelpikta 
 
## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing tests pass with my changes

2019-07-24 11:52 UTC, pavelpikta approved these changes
LGTM

2019-07-24 12:04 UTC, tgadiev requested changes
Please update tests with last ADK templates

2019-07-24 12:04 UTC, tgadiev commented on molecule/cloud-aws-direct-5.5/molecule.yml
> +    image: ami-9887c6e7
Add platform field

2019-07-24 12:04 UTC, tgadiev commented on molecule/cloud-aws-direct-5.5/molecule.yml
>      image: ami-1585c46a
Add platform field

2019-07-24 12:04 UTC, tgadiev commented on molecule/cloud-aws-direct-5.6/molecule.yml
>      instance_type: m5.large
Add platform field

2019-07-24 12:04 UTC, tgadiev commented on molecule/cloud-aws-direct-5.6/molecule.yml
>      instance_type: m4.large
Add platform field

2019-07-24 12:04 UTC, tgadiev commented on molecule/cloud-aws-direct-5.6/molecule.yml
>      instance_type: m5.large
Add platform field

2019-07-24 12:04 UTC, tgadiev commented on molecule/cloud-aws-direct-5.7/molecule.yml
>      instance_type: m5.large
Add platform field

2019-07-24 12:04 UTC, tgadiev commented on molecule/cloud-aws-direct-5.7/molecule.yml
>      instance_type: m4.large
Add platform field

2019-07-24 12:04 UTC, tgadiev commented on molecule/resources/provisioning/AWS/create.yml
>  - name: Create
That file should be removed. We use external molecule drivers from its own repository.

2019-07-24 12:04 UTC, tgadiev commented on molecule/resources/provisioning/AWS/destroy.yml
>  - name: Destroy
File should be removed

2019-08-05 12:28 UTC, tgadiev approved these changes

2019-08-05 12:40 UTC, merged